# Generated by Django 5.0.2 on 2024-03-06 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=13, verbose_name='Phone')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/avatars', verbose_name='Image')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is user active')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is Superuser')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='title')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active role')),
            ],
        ),
        migrations.CreateModel(
            name='SquadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Squad type name')),
            ],
        ),
        migrations.CreateModel(
            name='VolunterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Volunter type name')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=254, verbose_name='Full name')),
                ('passport_id', models.CharField(blank=True, max_length=254, null=True, verbose_name='Passport')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.role'),
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='user_to_squad', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('squad_name', models.CharField(max_length=254, verbose_name='squad name')),
                ('squad_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.squadtype', verbose_name='Squad type name')),
            ],
        ),
        migrations.CreateModel(
            name='Volunter',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='user_to_volunter', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Full name')),
                ('organization_name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Organization name')),
                ('is_organisation', models.BooleanField(default=False, verbose_name='Is organisation or individual')),
                ('volunter_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.voluntertype', verbose_name='Volunter type name')),
            ],
        ),
    ]
