# Generated by Django 5.0.2 on 2024-03-01 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=13, verbose_name='Phone')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/avatars', verbose_name='Image')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is user active')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is Superuser')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SquadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Squad type name')),
            ],
        ),
        migrations.CreateModel(
            name='VolunterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Volunter type name')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=254, verbose_name='Full name')),
                ('passport_id', models.CharField(blank=True, max_length=254, null=True, verbose_name='Passport')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('squad_name', models.CharField(max_length=254, verbose_name='squad name')),
                ('squad_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.squadtype', verbose_name='Squad type name')),
            ],
        ),
        migrations.CreateModel(
            name='Volunter',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Full name')),
                ('organization_name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Organization name')),
                ('is_organisation', models.BooleanField(default=False, verbose_name='Is organisation or individual')),
                ('volunter_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.voluntertype', verbose_name='Volunter type name')),
            ],
        ),
    ]
