version: '3'
services:
  db:
    image: postgres
    container_name: pgdb
    env_file:
      - ./.env
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    expose:
      - 5432


  web:
    container_name: mavu-site
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn tspp.asgi:application --workers 4 --log-level debug --timeout 120 --bind 0.0.0.0:8000 --reload"
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      - reverse-proxy
    volumes:
      - static_volume:/src/staticfiles
      - media_volume:/src/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`mavu.pp.ua`)"

  nginx:
    container_name: statics
    image: nginx:alpine
    restart: always
    expose:
      - 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`mavu.pp.ua`) && PathPrefix(`/static`)"
      - "traefik.http.routers.nginx.rule=Host(`mavu.pp.ua`) && PathPrefix(`/media`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    depends_on:
      - web
  
  reverse-proxy:
    image: traefik:v2.10
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - /root/certificates:/ssl-certs/



volumes:
  pgdbdata: null
  static_volume: null
  media_volume: null

