# Generated by Django 5.0.2 on 2024-03-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
